### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by moussaif-design** [infobyte/faraday-cli#12]
┌──(root㉿kali)-[~] └─# faraday-cli auth Traceback (most recent call last):   File "/usr/local/bin/faraday-cli", line 5, in <module>     from faraday_cli.shell.main import main ModuleNotFoundError: No module named 'faraday_cli'

**Comment by f-amato** [comment]
Hello, @moussaif-design thanks for using faraday and reporting this. We are going to investigate and let you know about this issue
