### ISSUE TITLE
TypeError on almost every function

### ISSUE THREAD

**Issue by caseybecking** [infobyte/faraday-cli#16]
About all i can do is authenticate, after that it error's out on almost everything i attempt.

`✔ Authenticated with faraday: http://127.0.0.1:5985
Faraday> workspace list
EXCEPTION of type 'Exception' occurred with message: Unknown error: <class 'TypeError'> - string indices must be integers
`

This is an example but even a select of the workspace does the same.

**Comment by caseybecking** [comment]
`pip freeze
aenum==3.1.11
aiohttp==3.8.3
aiosignal==1.3.1
anyio==4.2.0
appdirs==1.4.4
apsw==3.34.0.post1
arandr==0.1.10
arrow==1.3.0
async-timeout==4.0.2
attrs==22.2.0
bcrypt==3.1.7
beautifulsoup4==4.9.3
blessed==1.17.6
borgbackup==1.1.16
boto3==1.16.49
botocore==1.19.49
Brlapi==0.8.2
build==0.10.0
cachetools==4.2.4
cairocffi==1.5.1
CairoSVG==2.7.0
certifi==2020.6.20
cffi==1.15.1
chardet==4.0.0
charset-normalizer==2.1.1
chrome-gnome-shell==0.0.0
click==8.1.3
cmd2==2.4.3
colorama==0.4.4
coloredlogs==7.3
configobj==5.0.6
cryptography==3.3.2
css-parser==1.0.6
cssselect==1.1.0
cssselect2==0.7.0
cssutils==1.0.2
cupshelpers==1.0
DateTime==5.0
dblatex==0.3.12
dbus-python==1.2.16
defusedxml==0.7.1
distlib==0.3.1
distro==1.5.0
distro-info==1.0
dnspython==2.0.0
ecdsa==0.18.0
evdev==1.6.1
exceptiongroup==1.2.0
eyeD3==0.8.10
faraday-cli==2.1.10
faraday-plugins==1.16.0
feedparser==5.2.1
fido2==0.9.1
filelock==3.0.12
filetype==1.2.0
flatdict==4.0.1
frozenlist==1.3.3
google-api-core==1.31.5
google-api-python-client==1.12.11
google-auth-httplib2==0.1.0
google-cloud==0.34.0
googleapis-common-protos==1.52.0
gpodder==3.10.17
Guake==3.6.3
h11==0.14.0
hid-parser==0.0.3
html2text==2020.1.16
html5-parser==0.4.9
html5lib==1.1
httpcore==1.0.2
httplib2==0.18.1
httpx==0.26.0
humanfriendly==9.1
idna==2.10
ifaddr==0.1.7
img2pdf==0.4.0
importlib-metadata==1.6.0
indicator-sound-switcher==2.2.2
inquirer==2.7.0
jeepney==0.6.0
Jinja2==2.11.3
jmespath==0.10.0
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
kaptan==0.5.10
keyring==22.0.1
libtmux==0.8.2
llfuse==1.3.8
log-symbols==0.0.14
louis==3.16.0
luddite==1.0.3
lxml==4.6.3
Mako==1.1.3
Markdown==3.3.4
MarkupSafe==1.1.1
mechanize==0.4.5
more-itertools==4.2.0
msgpack==1.0.0
multidict==6.0.4
mygpoclient==1.8
netifaces==0.10.9
oauthlib==3.2.2
ocrmypdf==10.3.1+dfsg
okta==2.8.0
olefile==0.46
packaging==23.0
pbr==5.5.0
pdfminer.six==20200726
pikepdf==1.17.3+dfsg
Pillow==9.5.0
pip-tools==6.12.2
pipenv==2022.12.19
pluggy==0.13.0
podcastparser==0.6.5
protobuf==4.21.12
proton-core==0.1.16
proton-keyring-linux==0.0.1
proton-keyring-linux-secretservice==0.0.1
proton-vpn-api-core==0.20.3
proton-vpn-connection==0.11.3
proton-vpn-gtk-app==4.1.10
proton-vpn-killswitch==0.2.0
proton-vpn-killswitch-network-manager==0.2.0
proton-vpn-logger==0.2.1
proton-vpn-network-manager==0.3.3
proton-vpn-network-manager-openvpn==0.0.4
proton-vpn-session==0.6.5
psutil==5.8.0
py-sneakers==1.0.1
py7zr==0.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pychm==0.8.6
pycparser==2.21
pycryptodome==3.17
pycryptodomex==3.9.7
pycups==2.0.1
pycurl==7.43.0.6
pydash==6.0.0
Pygments==2.7.1
PyGObject==3.38.0
PyNaCl==1.4.0
pynput==1.7.6
pyOpenSSL==20.0.1
pyparsing==3.0.9
pyperclip==1.8.2
pyproject-hooks==1.0.0
PyQt5==5.15.2
PyQt5-sip==12.8.1
PyQtWebEngine==5.15.2
pyscard==2.0.0
PySide6==6.5.0
PySide6-Addons==6.5.0
PySide6-Essentials==6.5.0
PySimpleSOAP==1.16.2
pysmbc==1.0.23
python-apt==2.2.1
python-dateutil==2.8.2
python-debian==0.1.39
python-debianbts==3.1.0
python-editor==1.0.4
python-git-info==0.8.3
python-gnupg==0.4.6
python-jose==3.3.0
python-magic==0.4.20
python-slugify==8.0.4
python-status==1.0.1
python-xapp==2.0.2
python-xlib==0.33
pythondialog==3.5.1
pytz==2022.7.1
pyudev==0.24.1
pyxdg==0.27
PyYAML==6.0
readchar==2.0.1
referencing==0.33.0
regex==2020.11.13
reportbug==7.10.3+deb11u1
reportlab==3.5.59
repoze.lru==0.7
requests==2.25.1
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
Routes==2.5.1
rpds-py==0.17.1
rsa==4.9
s3transfer==0.3.7
SecretStorage==3.3.1
shiboken6==6.5.0
simple-rest-client==1.2.1
simplejson==3.17.2
six==1.16.0
sniffio==1.3.0
solaar==1.1.9
sortedcontainers==2.1.0
soupsieve==2.2.1
spinners==0.0.24
streamdeck==0.9.3
streamdeck-ui==2.0.15
systemd-python==234
tabulate==0.9.0
termcolor==2.4.0
terminator==2.1.0
text-unidecode==1.3
texttable==1.6.3
tinycss2==1.2.1
tmuxp==1.7.0
tomli==2.0.1
tqdm==4.57.0
types-python-dateutil==2.8.19.20240106
typing-extensions==4.9.0
unattended-upgrades==0.1
uritemplate==3.0.1
urllib3==1.26.5
validators==0.22.0
vboxapi==1.0
virtualenv==20.4.0+ds
virtualenv-clone==0.5.7
wcwidth==0.2.6
webencodings==0.5.1
WebOb==1.8.6
xdg==5
xmltodict==0.13.0
yarl==1.8.2
yubikey-manager==4.0.0a1
zeroconf==0.26.1
zipp==1.0.0
zope.interface==5.5.2
`

When running the workspace list command this is the log that is written 

`2024-02-09T07:19:39-0800 - geventwebsocket.handler - INFO {Dummy-24} [pid:3521094] [handler.py:242 - log_request()]  127.0.0.1 - - [2024-02-09 07:19:39] "GET /_api/v3/ws HTTP/1.1" 200 749 0.404944`

**Comment by ezk06eer** [comment]
please share:

python version
OS
faraday version

also check your bash profile and share with redacted information:

/etc/profile
~/.bash_profile
~/.bash_login
~/.profile

Can you reauthenticate on faraday-cli?

Cheers!

**Comment by caseybecking** [comment]
I've tried both ways of running it (docker and locally) - currently im runnig it locally - here are some outputs that may help - 
`
cat /etc/*rel*
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`
`
python --version
Python 3.9.2
`
![screenshot-20240209-160052Z-selected](https://github.com/infobyte/faraday-cli/assets/139295/9e706355-0b66-4559-bfc4-1637afe81798)

Before i share bash files, what would cause issues within those?

**Comment by ezk06eer** [comment]
@caseybecking i just checked on a fresh installed faraday 5.1.0 in docker, and a fresh virtual environment to install faraday-cli and i cannot replicate your issue, could you check making a backup of ~/.faraday and renaming the folder to .faraday.bkp also making a fresh docker compose up?

create a new virtualenv for faraday-cli then install it fresh

faraday-cli is not breacking on our local deploy.

try a fresh vitualenv and let me know how its going, everything points out to a failed environment in your local.


```bash
  ~ faraday-cli auth

Faraday url [https://demo2.apps.faradaysec.com]: http://127.0.0.1:5985

User: faraday

Password:
Saving config
✔ Authenticated with faraday: http://127.0.0.1:5985

➜  ~ faraday-cli

    ______                     __               _________
   / ____/___ __________ _____/ /___ ___  __   / ____/ (_)
  / /_  / __ `/ ___/ __ `/ __  / __ `/ / / /  / /   / / /
 / __/ / /_/ / /  / /_/ / /_/ / /_/ / /_/ /  / /___/ / /
/_/    \__,_/_/   \__,_/\__,_/\__,_/\__, /   \____/_/_/
                                   /____/

v:2.1.10
Server: http://127.0.0.1:5985
Faraday> workspace list
No workspaces available
Faraday> version
faraday-cli: 2.1.10
Faraday> workspace list
NAME          HOSTS    SERVICES    VULNS  ACTIVE    PUBLIC    READONLY
----------  -------  ----------  -------  --------  --------  ----------
workspace1        1           0        1  True      False     False
```

**Comment by caseybecking** [comment]
Ok, i will give this a try shortly - Thank You!

**Comment by ezk06eer** [comment]
Hi @caseybecking from your report we continued investigating, and with faraday 5.0.1 the cli works just fine but with the latest update its not working, we will move as fast as we can to release a version that complies and has all the needed tools to be fixed.

Thanks a lot for your report we helped a lot with our process!🥇🥇🥇

**Comment by caseybecking** [comment]
Thank you - I will check back once this has a PR for testing.

**Comment by ezk06eer** [comment]
there is a new release for faraday cli on which you will be able to use it again. Thanks again for reporting this!

**Comment by ezk06eer** [comment]
Hi, the change is released in the latest, so all of the commands should
work as expected.

Thanks for your colab!

The faraday team
