### ISSUE TITLE
Faraday-cli Auth compatible and some other issues

### ISSUE THREAD

**Issue by dmknght** [infobyte/faraday-cli#5]
OS: Parrot 4.10
Python: 3.9.1
Faraday server: 3.14
Faraday cli: should be 1.0.1 which was installed from pip3
Some issues:
1. [FIXED] Program failed to start, can't import module from cmd2. Debian's package is older than faraday-cli's requirement. Fixed by `sudo pip3 install cmd2 -U` to upgrade it
2. Need better handler for server not found: When user start client and server wasn't started, banner shows `Missing faraday server, run 'auth'` But when user auth (server didn't run), the traceback msg showed.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 861, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection_pool.py", line 218, in request
    response = connection.request(
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection.py", line 93, in request
    self.socket = self._open_socket(timeout)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection.py", line 119, in _open_socket
    return self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_backends/sync.py", line 143, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [Errno 111] Connection refused
```
-> This should be an msg: `Can't connect to server` instead. Could be `check your connection` or server didn't start. 
3. Try login after start server: After provide credentials (login web ui works and gtk client works), cli showed error `Invalid credentials`.

**Comment by aenima-x** [comment]
Yes the cmd2 version is a known issue, we have to specify the min version of cmd2.
I will fix the message.
I don't know what yo tell you about the credentials issue.

You could try to run a tcpdump or use a proxy to compare the request with the one made by the web.

**Comment by dmknght** [comment]
> You could try to run a tcpdump or use a proxy to compare the request with the one made by the web.

You are right. Let me try this. Maybe i should edit source code a bit to check the return value.
P/s: Would the `auth` supports proxy connection as optional argument? I meant it makes sense if faraday server is inside Enterprise environment and somehow a proxy is needed to connect
p/s2: I forgot: when user type enter for empty URL, should CLI force default URL `http://localhost:5985` instead of keep telling users provide URL? I mean users are lazy sometimes

**Comment by aenima-x** [comment]
if you export the HTTP_PROXY variable before execute the cli, it will use it.

No, the proxy is just to see the request..it doesn´t make any sense use proxy with the cli.
If the auth is of then the next time the cli will offer the last url.
You dont need to write it again

**Comment by aenima-x** [comment]
Can you tell me the version of the faraday server?

**Comment by dmknght** [comment]
>  So if you enter localhost as server you will not see it in the proxy.

Well i meant proxy will be optional setting (like using argument for auth command?) and it will be used for non localhost addresses but you are right it is not very neccessary.
