### ISSUE TITLE
Validate from API show return code 401 unauthorized

### ISSUE THREAD

**Issue by dmknght** [infobyte/faraday-cli#7]
I'm porting the API source code to Nim lang to develop my GUI version of new Faraday CLI. When i try the validate, i am seeing error code like title. The code is at https://github.com/infobyte/faraday-cli/blob/c3fada4075608d22c84ba267517b74ee4ed4ef54/faraday_cli/api_client/faraday_api.py#L158
The weird problem is it happens when i run command `status` from `faraday-cli` as well. Screenshot when i capture with wireshark
![image](https://user-images.githubusercontent.com/29118926/112272486-2c2a5980-8c74-11eb-87a5-c42c96b7446e.png)
My request from Nim http client
![image](https://user-images.githubusercontent.com/29118926/112272575-4d8b4580-8c74-11eb-990b-9076aeb75ba4.png)

IDK if uppercase could make any problem but i believe `validate` is having error. My faraday server version
```
Package: faraday
Version: 3.14.2-0kali1
```

**Comment by dmknght** [comment]
Login again doesn't help
![image](https://user-images.githubusercontent.com/29118926/112274101-03a35f00-8c76-11eb-8195-6fa44eec609a.png)

**Comment by dmknght** [comment]
I have to delete `~/.faraday-cli.yml` to fix problem. What could be wrong here?

**Comment by aenima-x** [comment]
Verify that you are up to date with master (of faraday cli), there was an issue fixed recently with the authentication

**Comment by dmknght** [comment]
> other posibility is that your token has expired.
by default only is valid for 12 hours, you can change that durarion in the faraday server.ini.
you need to run “auth” again

Likely after "auth", user have to exit the cli. I've cloned and setup the latest faraday-cli and i'll check this problem again. I think for now it can be closed

**Comment by aenima-x** [comment]
@dmknght the bug that you have to exit the cli after auth is fixed in the next release ;)

**Comment by dmknght** [comment]
Thank you for that information. I've just tested it again and it was not my mistake. I think the fix is really easy :D
