### ISSUE TITLE
Shell.py Error | __init__() missing 1 required positional argument: 'settable_object'

### ISSUE THREAD

**Issue by WhosFerny** [infobyte/faraday-cli#8]
OS: Kali GNU/Linux 2021.2
Python: 3.9.2
Faraday server: 3.15.0
Faraday cli: 1.1.0
Issue:

After following the installation guide, I get this error when trying to authenticate with the server:

![image](https://user-images.githubusercontent.com/61771140/121256648-c749cd00-c87a-11eb-93ef-6cb0f396cd6e.png)

Any ideas?

**Comment by helium876** [comment]
Try this out 

pip install cmd2==1.5.0 --force-reinstall

**Comment by aenima-x** [comment]
@helium876 Thanks, I will fix this tomorrow

**Comment by WhosFerny** [comment]
> Try this out
> 
> pip install cmd2==1.5.0 --force-reinstall

Yep, that fixed it. Thank you.
